{"name": "test_case[阿里巴巴]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'appium_xueqiu/app/data/main.yml'", "trace": "self = <testcase.test_search.TestCase object at 0x046C62B0>\n\n    def setup(self):\n>       self.search = App().start().main().goto_market().goto_search()\n\ntest_search.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\page\\main.py:11: in goto_market\n    self.steps(\"appium_xueqiu/app/data/main.yml\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <appium_xueqiu.app.page.main.Main object at 0x046C6640>, path = 'appium_xueqiu/app/data/main.yml'\n\n    def steps(self, path):\n>       with open(path, encoding=\"utf-8\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'appium_xueqiu/app/data/main.yml'\n\n..\\page\\base_page.py:45: FileNotFoundError"}, "parameters": [{"name": "name", "value": "'阿里巴巴'"}], "start": 1592552368613, "stop": 1592552368613, "uuid": "02a59f17-c1a7-4998-838d-50fe1684776a", "historyId": "4d9d8c6f0dbf7d5dded05f6049178f37", "testCaseId": "db9c3a001a2306c35db9df4100f25b34", "fullName": "test_search.TestCase#test_case", "labels": [{"name": "suite", "value": "test_search"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "LAPTOP-MGCADPUS"}, {"name": "thread", "value": "20340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_search"}]}