{"name": "test_case[阿里巴巴]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../../data/search.yml'", "trace": "self = <testcase.test_search.TestCase object at 0x03E54088>, name = '阿里巴巴'\n\n    @pytest.mark.parametrize(\"name\", yaml.safe_load(open(\"./test_search.yaml\", encoding=\"utf-8\")))\n    def test_case(self, name):\n>       self.search.search(name)\n\ntest_search.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\page\\search.py:7: in search\n    self.steps(\"../../data/search.yml\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <appium_xueqiu.app.page.search.Search object at 0x03E54610>, path = '../../data/search.yml'\n\n    def steps(self, path):\n>       with open(path, encoding=\"utf-8\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../../data/search.yml'\n\n..\\page\\base_page.py:45: FileNotFoundError"}, "parameters": [{"name": "name", "value": "'阿里巴巴'"}], "start": 1592557183391, "stop": 1592557183392, "uuid": "e4877a34-4d0a-4753-98d2-ba41c61db2f7", "historyId": "4d9d8c6f0dbf7d5dded05f6049178f37", "testCaseId": "db9c3a001a2306c35db9df4100f25b34", "fullName": "test_search.TestCase#test_case", "labels": [{"name": "suite", "value": "test_search"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "LAPTOP-MGCADPUS"}, {"name": "thread", "value": "6380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_search"}]}